name: Spotify Badge

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  spotify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate Spotify Badge
        uses: andnj/spotify-readme@main
        with:
          client_id: ${{ secrets.SPOTIFY_CLIENT_ID }}
          client_secret: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          refresh_token: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          output: dist/spotify.svg

      - name: Push Spotify Badge
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
